package org.motechproject.mcts.integration.mds.model;

// Generated Jun 7, 2014 2:48:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * HubTransaction generated by hbm2java
 */
@Entity
public class HubTransaction implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = 8519082727068392956L;
	private Date startDate;
	private Date endDate;
	private Boolean isNotified;

	public HubTransaction() {
	}

	public HubTransaction(int id, Date startDate, Date endDate,
			Boolean isNotified) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.isNotified = isNotified;
	}

	@Field
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Field
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Field
	public Boolean getIsNotified() {
		return this.isNotified;
	}

	public void setIsNotified(Boolean isNotified) {
		this.isNotified = isNotified;
	}

}
