package org.motechproject.mcts.integration.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.jdo.annotations.Unique;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsPhc generated by hbm2java
 */
@Entity
@Unique(members = {
        "phcId", "mctsHealthblock" })
public class MctsPhc implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1454403942048262339L;
    private MctsHealthblock mctsHealthblock;
    private int phcId;
    private String name;
    private boolean status;
    private Set<MctsSubcenter> mctsSubcenters = new HashSet<MctsSubcenter>(0);
    private Set<MctsHealthworker> mctsHealthworkers = new HashSet<MctsHealthworker>(
            0);

    public MctsPhc() {
    }

    public MctsPhc(MctsHealthblock mctsHealthblock, int phcId, String name) {
        this.mctsHealthblock = mctsHealthblock;
        this.phcId = phcId;
        this.name = name;
    }

    public MctsPhc(MctsHealthblock mctsHealthblock, int phcId, String name,
            Set<MctsSubcenter> mctsSubcenters,
            Set<MctsHealthworker> mctsHealthworkers, boolean status) {
        this.mctsHealthblock = mctsHealthblock;
        this.phcId = phcId;
        this.name = name;
        this.mctsSubcenters = mctsSubcenters;
        this.mctsHealthworkers = mctsHealthworkers;
        this.status = status;
    }

 
    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsHealthblock getMctsHealthblock() {
        return this.mctsHealthblock;
    }

    public void setMctsHealthblock(MctsHealthblock mctsHealthblock) {
        this.mctsHealthblock = mctsHealthblock;
    }

    @Field(required = true)
    public int getPhcId() {
        return this.phcId;
    }

    public void setPhcId(int phcId) {
        this.phcId = phcId;
    }

    @Field(required = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Field
    public Set<MctsSubcenter> getMctsSubcenters() {
        return this.mctsSubcenters;
    }

    public void setMctsSubcenters(Set<MctsSubcenter> mctsSubcenters) {
        this.mctsSubcenters = mctsSubcenters;
    }

    @Field
    public Set<MctsHealthworker> getMctsHealthworkers() {
        return this.mctsHealthworkers;
    }

    public void setMctsHealthworkers(Set<MctsHealthworker> mctsHealthworkers) {
        this.mctsHealthworkers = mctsHealthworkers;
    }

}
