package org.motechproject.mcts.integration.mds.model;

// Generated May 30, 2014 4:28:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.jdo.annotations.Unique;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsHealthworker generated by hbm2java
 */
@Entity
@Unique(members = { "healthworker_id", "subcenter_id" })
public class MctsHealthworker implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6071024488249276636L;
    private MctsPhc mctsPhc;
    private MctsSubcenter mctsSubcenter;
    private MctsVillage mctsVillage;
    private int healthworkerId;
    private String name;
    private String contactNo;
    private String sex;
    private String type;
    private String husbandName;
    private String aadharNo;
    private String gfAddress;
    private String careGroupid;
    private boolean status;
    private Set<MctsPregnantMother> mctsPregnantMothersForAshaId = new HashSet<MctsPregnantMother>(
            0);
    private Set<MctsPregnantMother> mctsPregnantMothersForAnmId = new HashSet<MctsPregnantMother>(
            0);

    public MctsHealthworker() {
    }

    public MctsHealthworker(MctsPhc mctsPhc, int healthworkerId, String name,
            String sex, String type) {
        this.mctsPhc = mctsPhc;
        this.healthworkerId = healthworkerId;
        this.name = name;
        this.sex = sex;
        this.type = type;
    }

    public MctsHealthworker(MctsPhc mctsPhc, MctsSubcenter mctsSubcenter,
            MctsVillage mctsVillage, int healthworkerId, String name,
            String contactNo, String sex, String type, String husbandName,
            String aadharNo, String gfAddress, String careGroupid,
            Set<MctsPregnantMother> mctsPregnantMothersForAshaId,
            Set<MctsPregnantMother> mctsPregnantMothersForAnmId, boolean status) {
        this.mctsPhc = mctsPhc;
        this.mctsSubcenter = mctsSubcenter;
        this.mctsVillage = mctsVillage;
        this.healthworkerId = healthworkerId;
        this.name = name;
        this.contactNo = contactNo;
        this.sex = sex;
        this.type = type;
        this.husbandName = husbandName;
        this.aadharNo = aadharNo;
        this.gfAddress = gfAddress;
        this.careGroupid = careGroupid;
        this.mctsPregnantMothersForAshaId = mctsPregnantMothersForAshaId;
        this.mctsPregnantMothersForAnmId = mctsPregnantMothersForAnmId;
        this.status = status;
    }


    
    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsPhc getMctsPhc() {
        return this.mctsPhc;
    }

    public void setMctsPhc(MctsPhc mctsPhc) {
        this.mctsPhc = mctsPhc;
    }

   
    @Field
    @Cascade(persist = true, update = true, delete = false)
    public MctsSubcenter getMctsSubcenter() {
        return this.mctsSubcenter;
    }

    public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
        this.mctsSubcenter = mctsSubcenter;
    }

    
    @Field
    @Cascade(persist = true, update = true, delete = false)
    public MctsVillage getMctsVillage() {
        return this.mctsVillage;
    }

    public void setMctsVillage(MctsVillage mctsVillage) {
        this.mctsVillage = mctsVillage;
    }

    @Field(required = true)
    public int getHealthworkerId() {
        return this.healthworkerId;
    }

    public void setHealthworkerId(int healthworkerId) {
        this.healthworkerId = healthworkerId;
    }

    @Field
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field 
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Field
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Field(required = true)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Field 
    public String getHusbandName() {
        return this.husbandName;
    }

    public void setHusbandName(String husbandName) {
        this.husbandName = husbandName;
    }

    @Field 
    public String getAadharNo() {
        return this.aadharNo;
    }

    public void setAadharNo(String aadharNo) {
        this.aadharNo = aadharNo;
    }

    @Field
    public String getGfAddress() {
        return this.gfAddress;
    }

    public void setGfAddress(String gfAddress) {
        this.gfAddress = gfAddress;
    }

    @Field 
    public String getCareGroupid() {
        return this.careGroupid;
    }

    public void setCareGroupid(String careGroupid) {
        this.careGroupid = careGroupid;
    }

    @Field
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @Field
    public Set<MctsPregnantMother> getMctsPregnantMothersForAshaId() {
        return this.mctsPregnantMothersForAshaId;
    }

    public void setMctsPregnantMothersForAshaId(
            Set<MctsPregnantMother> mctsPregnantMothersForAshaId) {
        this.mctsPregnantMothersForAshaId = mctsPregnantMothersForAshaId;
    }

    @Field
    public Set<MctsPregnantMother> getMctsPregnantMothersForAnmId() {
        return this.mctsPregnantMothersForAnmId;
    }

    public void setMctsPregnantMothersForAnmId(
            Set<MctsPregnantMother> mctsPregnantMothersForAnmId) {
        this.mctsPregnantMothersForAnmId = mctsPregnantMothersForAnmId;
    }

}
