package org.motechproject.mcts.integration.mds.model;

// Generated May 26, 2014 2:25:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.jdo.annotations.Unique;

import org.motechproject.mcts.lookup.MCTSPregnantMotherCaseAuthorisedStatus;
import org.motechproject.mcts.lookup.MCTSPregnantMotherMatchStatus;
import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsPregnantMother generated by hbm2java
 */
@Entity
public class MctsPregnantMother implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2473057427181282155L;
	@Unique
	private String mctsPersonaCaseUId;
	private MctsPhc mctsPhc;
	private MctsSubcenter mctsSubcenter;
	private MctsHealthworker mctsHealthworkerByAshaId;
	private MCTSPregnantMotherMatchStatus mCTSPregnantMotherMatchStatus;
	private MctsHealthworker mctsHealthworkerByAnmId;
	private MotherCase motherCase;
	private MctsVillage mctsVillage;
	private MCTSPregnantMotherCaseAuthorisedStatus mCTSPregnantMotherCaseAuthorisedStatus;
	private String mctsId;
	private String name;
	private String hindiName;
	private String type;
	private Date birthDate;
	private String gender;
	private String fatherHusbandName;
	private String hindiFatherHusbandName;
	private String email;
	private String mobileNo;
	private String economicStatus;
	private String category;
	private String beneficiaryAddress;
	private String uidNumber;
	private String pincode;
	private Date lmpDate;
	private String eidNumber;
	private String ward;
	private String town;
	private Date creationTime;
	private String hhNumber;
	private String familyNumber;
	private String ownerId;
	private String dateOpened;

	public MctsPregnantMother() {
	}

	public MctsPregnantMother(
			MctsSubcenter mctsSubcenter,
			MctsHealthworker mctsHealthworkerByAshaId,
			MCTSPregnantMotherMatchStatus mCTSPregnantMotherMatchStatus,
			MctsHealthworker mctsHealthworkerByAnmId,
			MotherCase motherCase,
			MctsVillage mctsVillage,
			MCTSPregnantMotherCaseAuthorisedStatus mCTSPregnantMotherCaseAuthorisedStatus,
			String mctsId, String name, String hindiName, String type,
			Date birthDate, String gender, String fatherHusbandName,
			String hindiFatherHusbandName, String email, String mobileNo,
			String economicStatus, String category, String beneficiaryAddress,
			String uidNumber, String pincode, Date lmpDate, String eidNumber,
			String ward, String town, Date creationTime, String familyNumber,
			String hhNumber, String ownerId, String dateOpened) {
		this.mctsSubcenter = mctsSubcenter;
		this.mctsHealthworkerByAshaId = mctsHealthworkerByAshaId;
		this.mCTSPregnantMotherMatchStatus = mCTSPregnantMotherMatchStatus;
		this.mctsHealthworkerByAnmId = mctsHealthworkerByAnmId;
		this.motherCase = motherCase;
		this.mctsVillage = mctsVillage;
		this.mCTSPregnantMotherCaseAuthorisedStatus = mCTSPregnantMotherCaseAuthorisedStatus;
		this.mctsId = mctsId;
		this.name = name;
		this.hindiName = hindiName;
		this.type = type;
		this.birthDate = birthDate;
		this.gender = gender;
		this.fatherHusbandName = fatherHusbandName;
		this.hindiFatherHusbandName = hindiFatherHusbandName;
		this.email = email;
		this.mobileNo = mobileNo;
		this.economicStatus = economicStatus;
		this.category = category;
		this.beneficiaryAddress = beneficiaryAddress;
		this.uidNumber = uidNumber;
		this.pincode = pincode;
		this.lmpDate = lmpDate;
		this.eidNumber = eidNumber;
		this.ward = ward;
		this.town = town;
		this.creationTime = creationTime;
		this.familyNumber = familyNumber;
		this.hhNumber = hhNumber;
		this.ownerId = ownerId;
		this.dateOpened = dateOpened;

	}

	@Field
	public String getMctsPersonaCaseUId() {
		return mctsPersonaCaseUId;
	}

	public void setMctsPersonaCaseUId(String mctsPersonaCaseUId) {
		this.mctsPersonaCaseUId = mctsPersonaCaseUId;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsSubcenter getMctsSubcenter() {
		return this.mctsSubcenter;
	}

	public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
		this.mctsSubcenter = mctsSubcenter;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsHealthworker getMctsHealthworkerByAshaId() {
		return this.mctsHealthworkerByAshaId;
	}

	public void setMctsHealthworkerByAshaId(
			MctsHealthworker mctsHealthworkerByAshaId) {
		this.mctsHealthworkerByAshaId = mctsHealthworkerByAshaId;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsHealthworker getMctsHealthworkerByAnmId() {
		return this.mctsHealthworkerByAnmId;
	}

	public void setMctsHealthworkerByAnmId(
			MctsHealthworker mctsHealthworkerByAnmId) {
		this.mctsHealthworkerByAnmId = mctsHealthworkerByAnmId;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MotherCase getMotherCase() {
		return this.motherCase;
	}

	public void setMotherCase(MotherCase motherCase) {
		this.motherCase = motherCase;
	}
	
	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsPhc getMctsPhc() {
		return mctsPhc;
	}

	public void setMctsPhc(MctsPhc mctsPhc) {
		this.mctsPhc = mctsPhc;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsVillage getMctsVillage() {
		return this.mctsVillage;
	}

	public void setMctsVillage(MctsVillage mctsVillage) {
		this.mctsVillage = mctsVillage;
	}

	@Field
	public MCTSPregnantMotherMatchStatus getmCTSPregnantMotherMatchStatus() {
		return mCTSPregnantMotherMatchStatus;
	}

	public void setmCTSPregnantMotherMatchStatus(
			MCTSPregnantMotherMatchStatus mCTSPregnantMotherMatchStatus) {
		this.mCTSPregnantMotherMatchStatus = mCTSPregnantMotherMatchStatus;
	}

	@Field
	public MCTSPregnantMotherCaseAuthorisedStatus getmCTSPregnantMotherCaseAuthorisedStatus() {
		return mCTSPregnantMotherCaseAuthorisedStatus;
	}

	public void setmCTSPregnantMotherCaseAuthorisedStatus(
			MCTSPregnantMotherCaseAuthorisedStatus mCTSPregnantMotherCaseAuthorisedStatus) {
		this.mCTSPregnantMotherCaseAuthorisedStatus = mCTSPregnantMotherCaseAuthorisedStatus;
	}

	@Field
	public String getMctsId() {
		return this.mctsId;
	}

	public void setMctsId(String mctsId) {
		this.mctsId = mctsId;
	}

	@Field
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Field
	public String getHindiName() {
		return this.hindiName;
	}

	public void setHindiName(String hindiName) {
		this.hindiName = hindiName;
	}

	@Field
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Field
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Field
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Field
	public String getFatherHusbandName() {
		return this.fatherHusbandName;
	}

	public void setFatherHusbandName(String fatherHusbandName) {
		this.fatherHusbandName = fatherHusbandName;
	}

	@Field
	public String getHindiFatherHusbandName() {
		return this.hindiFatherHusbandName;
	}

	public void setHindiFatherHusbandName(String hindiFatherHusbandName) {
		this.hindiFatherHusbandName = hindiFatherHusbandName;
	}

	@Field
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Field
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Field
	public String getEconomicStatus() {
		return this.economicStatus;
	}

	public void setEconomicStatus(String economicStatus) {
		this.economicStatus = economicStatus;
	}

	@Field
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Field
	public String getBeneficiaryAddress() {
		return this.beneficiaryAddress;
	}

	public void setBeneficiaryAddress(String beneficiaryAddress) {
		this.beneficiaryAddress = beneficiaryAddress;
	}

	@Field
	public String getUidNumber() {
		return this.uidNumber;
	}

	public void setUidNumber(String uidNumber) {
		this.uidNumber = uidNumber;
	}

	@Field
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Field
	public Date getLmpDate() {
		return this.lmpDate;
	}

	public void setLmpDate(Date lmpDate) {
		this.lmpDate = lmpDate;
	}

	@Field
	public String getEidNumber() {
		return this.eidNumber;
	}

	public void setEidNumber(String eidNumber) {
		this.eidNumber = eidNumber;
	}

	@Field
	public String getWard() {
		return this.ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	@Field
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Field
	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	@Field
	public String getHhNumber() {
		return this.hhNumber;
	}

	public void setHhNumber(String hhNumber) {
		this.hhNumber = hhNumber;
	}

	@Field
	public String getFamilyNumber() {
		return this.familyNumber;
	}

	public void setFamilyNumber(String familyNumber) {
		this.familyNumber = familyNumber;
	}

	@Field
	public String getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	@Field
	public String getDateOpened() {
		return this.dateOpened;
	}

	public void setDateOpened(String dateOpened) {
		this.dateOpened = dateOpened;
	}

}