package org.motechproject.mcts.integration.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MctsPregnantMotherServiceUpdate generated by hbm2java
 */
@Entity
public class MctsPregnantMotherServiceUpdate implements java.io.Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = 367844207976936357L;
	private MctsPregnantMother mctsPregnantMother;
	private Integer serviceType;
	private Date serviceDeliveryDate;
	private Date serviceUpdateTime;

	public MctsPregnantMotherServiceUpdate() {
	}

	public MctsPregnantMotherServiceUpdate(
			MctsPregnantMother mctsPregnantMother, Integer serviceType,
			Date serviceDeliveryDate, Date serviceUpdateTime) {
		this.mctsPregnantMother = mctsPregnantMother;
		this.serviceType = serviceType;
		this.serviceDeliveryDate = serviceDeliveryDate;
		this.serviceUpdateTime = serviceUpdateTime;
	}

	@Field
	@Cascade(persist = true, update = true, delete = false)
	public MctsPregnantMother getMctsPregnantMother() {
		return this.mctsPregnantMother;
	}

	public void setMctsPregnantMother(MctsPregnantMother mctsPregnantMother) {
		this.mctsPregnantMother = mctsPregnantMother;
	}

	@Field
	public Integer getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	@Field
	public Date getServiceDeliveryDate() {
		return this.serviceDeliveryDate;
	}

	public void setServiceDeliveryDate(Date serviceDeliveryDate) {
		this.serviceDeliveryDate = serviceDeliveryDate;
	}

	@Field
	public Date getServiceUpdateTime() {
		return this.serviceUpdateTime;
	}

	public void setServiceUpdateTime(Date serviceUpdateTime) {
		this.serviceUpdateTime = serviceUpdateTime;
	}

}
