package org.motechproject.mcts.integration.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;

import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MctsFlwData generated by hbm2java
 */
@Entity
public class MctsHealthworkerErrorLog implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8389445771473205913L;
    private String districtId;
    private String talukaId;
    private String healthblockId;
    private String subcentreId;
    private String villageId;
    private String name;
    private String sex;
    private String type;
    private String aadharNo;
    private String husbandName;
    private String gfAddress;
    private String healthworkerId;
    private String contactNo;
    private String phcId;
    private String comments;

    public MctsHealthworkerErrorLog() {
    }

    public MctsHealthworkerErrorLog(String healthworkerId) {
        this.healthworkerId = healthworkerId;
    }

    public MctsHealthworkerErrorLog(String districtId, String talukaId,
            String healthblockId, String subcentreId, String villageId,
            String name, String sex, String type, String aadharNo,
            String husbandName, String gfAddress, String healthworkerId,
            String contactNo, String phcId, String comments) {
        this.districtId = districtId;
        this.talukaId = talukaId;
        this.healthblockId = healthblockId;
        this.subcentreId = subcentreId;
        this.villageId = villageId;
        this.name = name;
        this.sex = sex;
        this.type = type;
        this.aadharNo = aadharNo;
        this.husbandName = husbandName;
        this.gfAddress = gfAddress;
        this.healthworkerId = healthworkerId;
        this.contactNo = contactNo;
        this.phcId = phcId;
        this.comments = comments;
    }

    @Field
    public String getDistrictId() {
        return this.districtId;
    }

    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }

    @Field
    public String getTalukaId() {
        return this.talukaId;
    }

    public void setTalukaId(String talukaId) {
        this.talukaId = talukaId;
    }

    @Field
    public String getHealthblockId() {
        return this.healthblockId;
    }

    public void setHealthblockId(String healthblockId) {
        this.healthblockId = healthblockId;
    }

    @Field
    public String getSubcentreId() {
        return this.subcentreId;
    }

    public void setSubcentreId(String subcentreId) {
        this.subcentreId = subcentreId;
    }

    @Field
    public String getVillageId() {
        return this.villageId;
    }

    public void setVillageId(String villageId) {
        this.villageId = villageId;
    }

    @Field
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    @Field
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Field
    public String getAadharNo() {
        return this.aadharNo;
    }

    public void setAadharNo(String aadharNo) {
        this.aadharNo = aadharNo;
    }

    @Field
    public String getHusbandName() {
        return this.husbandName;
    }

    public void setHusbandName(String husbandName) {
        this.husbandName = husbandName;
    }

    @Field
    public String getGfAddress() {
        return this.gfAddress;
    }

    public void setGfAddress(String gfAddress) {
        this.gfAddress = gfAddress;
    }

    @Field(required = true)
    public String getHealthworkerId() {
        return this.healthworkerId;
    }

    public void setHealthworkerId(String healthworkerId) {
        this.healthworkerId = healthworkerId;
    }

    @Field
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Field
    public String getPhcId() {
        return this.phcId;
    }

    public void setPhcId(String phcId) {
        this.phcId = phcId;
    }

    @Field
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
