package org.motechproject.mcts.integration.mds.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.jdo.annotations.Unique;

import org.motechproject.mds.annotations.Cascade;
import org.motechproject.mds.annotations.Entity;
import org.motechproject.mds.annotations.Field;

/**
 * MctsVillage generated by hbm2java
 */
@Entity
@Unique(members = {
        "village_id", "subcenter_id", "taluk_id" })
public class MctsVillage implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -3995277117692611278L;
    private MctsTaluk mctsTaluk;
    private MctsSubcenter mctsSubcenter;
    private int villageId;
    private String name;
    private boolean status;
   
    public MctsVillage() {
    }

    public MctsVillage(MctsTaluk mctsTaluk, MctsSubcenter mctsSubcenter,
            int villageId, String name) {
        this.mctsTaluk = mctsTaluk;
        this.mctsSubcenter = mctsSubcenter;
        this.villageId = villageId;
        this.name = name;
    }

    public MctsVillage(MctsTaluk mctsTaluk, MctsSubcenter mctsSubcenter,
            int villageId, String name,
            Set<MctsHealthworker> mctsHealthworkers, boolean status) {
        this.mctsTaluk = mctsTaluk;
        this.mctsSubcenter = mctsSubcenter;
        this.villageId = villageId;
        this.name = name;
        this.status = status;
    }

    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsTaluk getMctsTaluk() {
        return this.mctsTaluk;
    }

    public void setMctsTaluk(MctsTaluk mctsTaluk) {
        this.mctsTaluk = mctsTaluk;
    }

    @Field(required = true)
    @Cascade(persist = true, update = true, delete = false)
    public MctsSubcenter getMctsSubcenter() {
        return this.mctsSubcenter;
    }

    public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
        this.mctsSubcenter = mctsSubcenter;
    }

    @Field(required = true)
    public int getVillageId() {
        return this.villageId;
    }

    public void setVillageId(int villageId) {
        this.villageId = villageId;
    }

    @Field(required = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Field
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

}
