package org.motechproject.mcts.integration.hibernate.model;

// Generated Jun 7, 2014 2:48:34 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HubTransaction generated by hbm2java
 */
@Entity
@Table(name = "hub_transaction", schema = "report")
public class HubTransaction implements java.io.Serializable {

	private int id;
	private Date startDate;
	private Date endDate;
	private Boolean isNotified;

	public HubTransaction() {
	}

	public HubTransaction(int id) {
		this.id = id;
	}

	public HubTransaction(int id, Date startDate, Date endDate,
			Boolean isNotified) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isNotified = isNotified;
	}

	@SequenceGenerator(name = "generator", sequenceName = "hub_transaction_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 29)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "is_notified")
	public Boolean getIsNotified() {
		return this.isNotified;
	}

	public void setIsNotified(Boolean isNotified) {
		this.isNotified = isNotified;
	}

}
