package org.motechproject.mcts.integration.hibernate.model;

// Generated May 30, 2014 4:28:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MctsHealthworker generated by hbm2java
 */
@Entity
@Table(name = "mcts_healthworker", schema = "report", uniqueConstraints = {
        @UniqueConstraint(columnNames = { "healthworker_id", "subcenter_id" }),
        @UniqueConstraint(columnNames = "healthworker_id") })
public class MctsHealthworker implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6071024488249276636L;
    private Integer id;
    private MctsPhc mctsPhc;
    private MctsSubcenter mctsSubcenter;
    private MctsVillage mctsVillage;
    private int healthworkerId;
    private String name;
    private String contactNo;
    private char sex;
    private String type;
    private String husbandName;
    private String aadharNo;
    private String gfAddress;
    private String careGroupid;
    private boolean status;
    private Set<MctsPregnantMother> mctsPregnantMothersForAshaId = new HashSet<MctsPregnantMother>(
            0);
    private Set<MctsPregnantMother> mctsPregnantMothersForAnmId = new HashSet<MctsPregnantMother>(
            0);

    public MctsHealthworker() {
    }

    public MctsHealthworker(MctsPhc mctsPhc, int healthworkerId, String name,
            char sex, String type) {
        this.mctsPhc = mctsPhc;
        this.healthworkerId = healthworkerId;
        this.name = name;
        this.sex = sex;
        this.type = type;
    }

    public MctsHealthworker(MctsPhc mctsPhc, MctsSubcenter mctsSubcenter,
            MctsVillage mctsVillage, int healthworkerId, String name,
            String contactNo, char sex, String type, String husbandName,
            String aadharNo, String gfAddress, String careGroupid,
            Set<MctsPregnantMother> mctsPregnantMothersForAshaId,
            Set<MctsPregnantMother> mctsPregnantMothersForAnmId, boolean status) {
        this.mctsPhc = mctsPhc;
        this.mctsSubcenter = mctsSubcenter;
        this.mctsVillage = mctsVillage;
        this.healthworkerId = healthworkerId;
        this.name = name;
        this.contactNo = contactNo;
        this.sex = sex;
        this.type = type;
        this.husbandName = husbandName;
        this.aadharNo = aadharNo;
        this.gfAddress = gfAddress;
        this.careGroupid = careGroupid;
        this.mctsPregnantMothersForAshaId = mctsPregnantMothersForAshaId;
        this.mctsPregnantMothersForAnmId = mctsPregnantMothersForAnmId;
        this.status = status;
    }

    @SequenceGenerator(name = "generator", sequenceName = "mcts_healthworker_id_seq")
    @Id
    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "phc_id", nullable = false)
    public MctsPhc getMctsPhc() {
        return this.mctsPhc;
    }

    public void setMctsPhc(MctsPhc mctsPhc) {
        this.mctsPhc = mctsPhc;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subcenter_id")
    public MctsSubcenter getMctsSubcenter() {
        return this.mctsSubcenter;
    }

    public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
        this.mctsSubcenter = mctsSubcenter;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "village_id")
    public MctsVillage getMctsVillage() {
        return this.mctsVillage;
    }

    public void setMctsVillage(MctsVillage mctsVillage) {
        this.mctsVillage = mctsVillage;
    }

    @Column(name = "healthworker_id", unique = true, nullable = false)
    public int getHealthworkerId() {
        return this.healthworkerId;
    }

    public void setHealthworkerId(int healthworkerId) {
        this.healthworkerId = healthworkerId;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "contact_no", length = 20)
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Column(name = "sex", length = 1)
    public char getSex() {
        return this.sex;
    }

    public void setSex(char sex) {
        this.sex = sex;
    }

    @Column(name = "type", nullable = false, length = 10)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "husband_name")
    public String getHusbandName() {
        return this.husbandName;
    }

    public void setHusbandName(String husbandName) {
        this.husbandName = husbandName;
    }

    @Column(name = "aadhar_no")
    public String getAadharNo() {
        return this.aadharNo;
    }

    public void setAadharNo(String aadharNo) {
        this.aadharNo = aadharNo;
    }

    @Column(name = "gf_address")
    public String getGfAddress() {
        return this.gfAddress;
    }

    public void setGfAddress(String gfAddress) {
        this.gfAddress = gfAddress;
    }

    @Column(name = "care_groupid")
    public String getCareGroupid() {
        return this.careGroupid;
    }

    public void setCareGroupid(String careGroupid) {
        this.careGroupid = careGroupid;
    }

    @Column(name = "status")
    public boolean getStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsHealthworkerByAshaId")
    public Set<MctsPregnantMother> getMctsPregnantMothersForAshaId() {
        return this.mctsPregnantMothersForAshaId;
    }

    public void setMctsPregnantMothersForAshaId(
            Set<MctsPregnantMother> mctsPregnantMothersForAshaId) {
        this.mctsPregnantMothersForAshaId = mctsPregnantMothersForAshaId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsHealthworkerByAnmId")
    public Set<MctsPregnantMother> getMctsPregnantMothersForAnmId() {
        return this.mctsPregnantMothersForAnmId;
    }

    public void setMctsPregnantMothersForAnmId(
            Set<MctsPregnantMother> mctsPregnantMothersForAnmId) {
        this.mctsPregnantMothersForAnmId = mctsPregnantMothersForAnmId;
    }

}
