package org.motechproject.mcts.integration.hibernate.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MctsFlwData generated by hbm2java
 */
@Entity
@Table(name = "mcts_healthworker_error_log", schema = "report")
public class MctsHealthworkerErrorLog implements java.io.Serializable {

	private Integer id;
	private String districtId;
	private String talukaId;
	private String healthblockId;
	private String subcentreId;
	private String villageId;
	private String name;
	private String sex;
	private String type;
	private String aadharNo;
	private String husbandName;
	private String gfAddress;
	private String healthworkerId;
	private String contactNo;
	private String phcId;
	private String comments;

	public MctsHealthworkerErrorLog() {
	}

	public MctsHealthworkerErrorLog(String healthworkerId) {
		this.healthworkerId = healthworkerId;
	}

	public MctsHealthworkerErrorLog(String districtId, String talukaId,
			String healthblockId, String subcentreId, String villageId,
			String name, String sex, String type, String aadharNo,
			String husbandName, String gfAddress, String healthworkerId,
			String contactNo, String phcId, String comments) {
		this.districtId = districtId;
		this.talukaId = talukaId;
		this.healthblockId = healthblockId;
		this.subcentreId = subcentreId;
		this.villageId = villageId;
		this.name = name;
		this.sex = sex;
		this.type = type;
		this.aadharNo = aadharNo;
		this.husbandName = husbandName;
		this.gfAddress = gfAddress;
		this.healthworkerId = healthworkerId;
		this.contactNo = contactNo;
		this.phcId = phcId;
		this.comments = comments;
	}

	@SequenceGenerator(name = "generator", sequenceName = "mcts_flw_data_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "district_id")
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	@Column(name = "taluka_id")
	public String getTalukaId() {
		return this.talukaId;
	}

	public void setTalukaId(String talukaId) {
		this.talukaId = talukaId;
	}

	@Column(name = "healthblock_id")
	public String getHealthblockId() {
		return this.healthblockId;
	}

	public void setHealthblockId(String healthblockId) {
		this.healthblockId = healthblockId;
	}

	@Column(name = "subcentre_id")
	public String getSubcentreId() {
		return this.subcentreId;
	}

	public void setSubcentreId(String subcentreId) {
		this.subcentreId = subcentreId;
	}

	@Column(name = "village_id")
	public String getVillageId() {
		return this.villageId;
	}

	public void setVillageId(String villageId) {
		this.villageId = villageId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "aadhar_no")
	public String getAadharNo() {
		return this.aadharNo;
	}

	public void setAadharNo(String aadharNo) {
		this.aadharNo = aadharNo;
	}

	@Column(name = "husband_name")
	public String getHusbandName() {
		return this.husbandName;
	}

	public void setHusbandName(String husbandName) {
		this.husbandName = husbandName;
	}

	@Column(name = "gf_address")
	public String getGfAddress() {
		return this.gfAddress;
	}

	public void setGfAddress(String gfAddress) {
		this.gfAddress = gfAddress;
	}

	@Column(name = "healthworker_id", nullable = false)
	public String getHealthworkerId() {
		return this.healthworkerId;
	}

	public void setHealthworkerId(String healthworkerId) {
		this.healthworkerId = healthworkerId;
	}

	@Column(name = "contact_no")
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "phc_id")
	public String getPhcId() {
		return this.phcId;
	}

	public void setPhcId(String phcId) {
		this.phcId = phcId;
	}

	

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
