package org.motechproject.mcts.integration.hibernate.model;

// Generated May 19, 2014 7:55:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MctsHealthblock generated by hbm2java
 */
@Entity
@Table(name = "mcts_healthblock", schema = "report", uniqueConstraints = @UniqueConstraint(columnNames = {
		"healthblock_id", "taluk_id" }))
public class MctsHealthblock implements java.io.Serializable {

	private Integer id;
	private MctsTaluk mctsTaluk;
	private int healthblockId;
	private String name;
	private Set<MctsPhc> mctsPhcs = new HashSet<MctsPhc>(0);

	public MctsHealthblock() {
	}

	public MctsHealthblock(MctsTaluk mctsTaluk, int healthblockId, String name) {
		this.mctsTaluk = mctsTaluk;
		this.healthblockId = healthblockId;
		this.name = name;
	}

	public MctsHealthblock(MctsTaluk mctsTaluk, int healthblockId, String name,
			Set<MctsPhc> mctsPhcs) {
		this.mctsTaluk = mctsTaluk;
		this.healthblockId = healthblockId;
		this.name = name;
		this.mctsPhcs = mctsPhcs;
	}

	@SequenceGenerator(name = "generator", sequenceName = "mcts_healthblock_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taluk_id", nullable = false)
	public MctsTaluk getMctsTaluk() {
		return this.mctsTaluk;
	}

	public void setMctsTaluk(MctsTaluk mctsTaluk) {
		this.mctsTaluk = mctsTaluk;
	}

	@Column(name = "healthblock_id", nullable = false)
	public int getHealthblockId() {
		return this.healthblockId;
	}

	public void setHealthblockId(int healthblockId) {
		this.healthblockId = healthblockId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsHealthblock")
	public Set<MctsPhc> getMctsPhcs() {
		return this.mctsPhcs;
	}

	public void setMctsPhcs(Set<MctsPhc> mctsPhcs) {
		this.mctsPhcs = mctsPhcs;
	}

}
