package org.motechproject.mcts.integration.hibernate.model;

// Generated May 14, 2014 11:43:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MctsHealthworker generated by hbm2java
 */
@Entity
@Table(name = "mcts_healthworker", schema = "report")
public class MctsHealthworker implements java.io.Serializable {

	private int id;
	private MctsSubcenter mctsSubcenter;
	private MctsVillage mctsVillage;
	private int healthworkerId;
	private String name;
	private int contactNo;
	private char sex;
	private String type;
	private String husbandName;
	private String aadharNo;
	private String gfAddress;

	public MctsHealthworker() {
	}

	public MctsHealthworker(int id, MctsSubcenter mctsSubcenter,
			int healthworkerId, String name, int contactNo, char sex,
			String type) {
		this.id = id;
		this.mctsSubcenter = mctsSubcenter;
		this.healthworkerId = healthworkerId;
		this.name = name;
		this.contactNo = contactNo;
		this.sex = sex;
		this.type = type;
	}

	public MctsHealthworker(int id, MctsSubcenter mctsSubcenter,
			MctsVillage mctsVillage, int healthworkerId, String name,
			int contactNo, char sex, String type, String husbandName,
			String aadharNo, String gfAddress) {
		this.id = id;
		this.mctsSubcenter = mctsSubcenter;
		this.mctsVillage = mctsVillage;
		this.healthworkerId = healthworkerId;
		this.name = name;
		this.contactNo = contactNo;
		this.sex = sex;
		this.type = type;
		this.husbandName = husbandName;
		this.aadharNo = aadharNo;
		this.gfAddress = gfAddress;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subcenter_id", nullable = false)
	public MctsSubcenter getMctsSubcenter() {
		return this.mctsSubcenter;
	}

	public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
		this.mctsSubcenter = mctsSubcenter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "village_id")
	public MctsVillage getMctsVillage() {
		return this.mctsVillage;
	}

	public void setMctsVillage(MctsVillage mctsVillage) {
		this.mctsVillage = mctsVillage;
	}

	@Column(name = "healthworker_id", nullable = false)
	public int getHealthworkerId() {
		return this.healthworkerId;
	}

	public void setHealthworkerId(int healthworkerId) {
		this.healthworkerId = healthworkerId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "contact_no", nullable = false)
	public int getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(int contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "sex", nullable = false, length = 1)
	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "husband_name")
	public String getHusbandName() {
		return this.husbandName;
	}

	public void setHusbandName(String husbandName) {
		this.husbandName = husbandName;
	}

	@Column(name = "aadhar_no")
	public String getAadharNo() {
		return this.aadharNo;
	}

	public void setAadharNo(String aadharNo) {
		this.aadharNo = aadharNo;
	}

	@Column(name = "gf_address")
	public String getGfAddress() {
		return this.gfAddress;
	}

	public void setGfAddress(String gfAddress) {
		this.gfAddress = gfAddress;
	}

}
