package org.motechproject.mcts.integration.hibernate.model;

// Generated May 14, 2014 4:50:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MctsPhc generated by hbm2java
 */
@Entity
@Table(name = "mcts_phc", schema = "report")
public class MctsPhc implements java.io.Serializable {

	private int id;
	private MctsHealthblock mctsHealthblock;
	private int phcId;
	private String name;
	private Set<MctsSubcenter> mctsSubcenters = new HashSet<MctsSubcenter>(0);

	public MctsPhc() {
	}

	public MctsPhc(int id, MctsHealthblock mctsHealthblock, int phcId,
			String name) {
		this.id = id;
		this.mctsHealthblock = mctsHealthblock;
		this.phcId = phcId;
		this.name = name;
	}

	public MctsPhc(int id, MctsHealthblock mctsHealthblock, int phcId,
			String name, Set<MctsSubcenter> mctsSubcenters) {
		this.id = id;
		this.mctsHealthblock = mctsHealthblock;
		this.phcId = phcId;
		this.name = name;
		this.mctsSubcenters = mctsSubcenters;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "healthblock_id", nullable = false)
	public MctsHealthblock getMctsHealthblock() {
		return this.mctsHealthblock;
	}

	public void setMctsHealthblock(MctsHealthblock mctsHealthblock) {
		this.mctsHealthblock = mctsHealthblock;
	}

	@Column(name = "phc_id", nullable = false)
	public int getPhcId() {
		return this.phcId;
	}

	public void setPhcId(int phcId) {
		this.phcId = phcId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsPhc")
	public Set<MctsSubcenter> getMctsSubcenters() {
		return this.mctsSubcenters;
	}

	public void setMctsSubcenters(Set<MctsSubcenter> mctsSubcenters) {
		this.mctsSubcenters = mctsSubcenters;
	}

}
