package org.motechproject.mcts.integration.hibernate.model;

// Generated May 14, 2014 4:50:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MctsHealthblock generated by hbm2java
 */
@Entity
@Table(name = "mcts_healthblock", schema = "report")
public class MctsHealthblock implements java.io.Serializable {

	private int id;
	private MctsTaluk mctsTaluk;
	private int healthblockId;
	private String name;
	private Set<MctsPhc> mctsPhcs = new HashSet<MctsPhc>(0);

	public MctsHealthblock() {
	}

	public MctsHealthblock(int id, MctsTaluk mctsTaluk, int healthblockId,
			String name) {
		this.id = id;
		this.mctsTaluk = mctsTaluk;
		this.healthblockId = healthblockId;
		this.name = name;
	}

	public MctsHealthblock(int id, MctsTaluk mctsTaluk, int healthblockId,
			String name, Set<MctsPhc> mctsPhcs) {
		this.id = id;
		this.mctsTaluk = mctsTaluk;
		this.healthblockId = healthblockId;
		this.name = name;
		this.mctsPhcs = mctsPhcs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taluk_id", nullable = false)
	public MctsTaluk getMctsTaluk() {
		return this.mctsTaluk;
	}

	public void setMctsTaluk(MctsTaluk mctsTaluk) {
		this.mctsTaluk = mctsTaluk;
	}

	@Column(name = "healthblock_id", nullable = false)
	public int getHealthblockId() {
		return this.healthblockId;
	}

	public void setHealthblockId(int healthblockId) {
		this.healthblockId = healthblockId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsHealthblock")
	public Set<MctsPhc> getMctsPhcs() {
		return this.mctsPhcs;
	}

	public void setMctsPhcs(Set<MctsPhc> mctsPhcs) {
		this.mctsPhcs = mctsPhcs;
	}

}
