package org.motechproject.mcts.integration.hibernate.model;

// Generated May 14, 2014 11:43:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MctsVillage generated by hbm2java
 */
@Entity
@Table(name = "mcts_village", schema = "report")
public class MctsVillage implements java.io.Serializable {

	private int id;
	private MctsTaluk mctsTaluk;
	private MctsSubcenter mctsSubcenter;
	private int villageId;
	private String name;
	private Set<MctsHealthworker> mctsHealthworkers = new HashSet<MctsHealthworker>(
			0);

	public MctsVillage() {
	}

	public MctsVillage(int id, MctsTaluk mctsTaluk,
			MctsSubcenter mctsSubcenter, int villageId, String name) {
		this.id = id;
		this.mctsTaluk = mctsTaluk;
		this.mctsSubcenter = mctsSubcenter;
		this.villageId = villageId;
		this.name = name;
	}

	public MctsVillage(int id, MctsTaluk mctsTaluk,
			MctsSubcenter mctsSubcenter, int villageId, String name,
			Set<MctsHealthworker> mctsHealthworkers) {
		this.id = id;
		this.mctsTaluk = mctsTaluk;
		this.mctsSubcenter = mctsSubcenter;
		this.villageId = villageId;
		this.name = name;
		this.mctsHealthworkers = mctsHealthworkers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taluk_id", nullable = false)
	public MctsTaluk getMctsTaluk() {
		return this.mctsTaluk;
	}

	public void setMctsTaluk(MctsTaluk mctsTaluk) {
		this.mctsTaluk = mctsTaluk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subcenter_id", nullable = false)
	public MctsSubcenter getMctsSubcenter() {
		return this.mctsSubcenter;
	}

	public void setMctsSubcenter(MctsSubcenter mctsSubcenter) {
		this.mctsSubcenter = mctsSubcenter;
	}

	@Column(name = "village_id", nullable = false)
	public int getVillageId() {
		return this.villageId;
	}

	public void setVillageId(int villageId) {
		this.villageId = villageId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsVillage")
	public Set<MctsHealthworker> getMctsHealthworkers() {
		return this.mctsHealthworkers;
	}

	public void setMctsHealthworkers(Set<MctsHealthworker> mctsHealthworkers) {
		this.mctsHealthworkers = mctsHealthworkers;
	}

}
