package org.motechproject.mcts.integration.hibernate.model;

// Generated May 14, 2014 11:43:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MctsPregnantMother generated by hbm2java
 */
@Entity
@Table(name = "mcts_pregnant_mother", schema = "report")
public class MctsPregnantMother implements java.io.Serializable {

	private int id;
	private MotherCase motherCase;
	private String mctsId;
	private String name;
	private String type;
	private Date birthDate;
	private Character gender;
	private String villageId;
	private String subcenterId;
	private String fatherHusbandName;
	private String email;
	private String mobileNo;
	private String economicStatus;
	private String category;
	private String beneficiaryAddress;
	private String uidNumber;
	private String pincode;
	private Date lmpDate;
	private String eidNumber;
	private String anmId;
	private String ward;
	private String town;
	private Set<MctsPregnantMotherServiceUpdate> mctsPregnantMotherServiceUpdates = new HashSet<MctsPregnantMotherServiceUpdate>(
			0);

	public MctsPregnantMother() {
	}

	public MctsPregnantMother(int id, MotherCase motherCase) {
		this.id = id;
		this.motherCase = motherCase;
	}

	public MctsPregnantMother(
			int id,
			MotherCase motherCase,
			String mctsId,
			String name,
			String type,
			Date birthDate,
			Character gender,
			String villageId,
			String subcenterId,
			String fatherHusbandName,
			String email,
			String mobileNo,
			String economicStatus,
			String category,
			String beneficiaryAddress,
			String uidNumber,
			String pincode,
			Date lmpDate,
			String eidNumber,
			String anmId,
			String ward,
			String town,
			Set<MctsPregnantMotherServiceUpdate> mctsPregnantMotherServiceUpdates) {
		this.id = id;
		this.motherCase = motherCase;
		this.mctsId = mctsId;
		this.name = name;
		this.type = type;
		this.birthDate = birthDate;
		this.gender = gender;
		this.villageId = villageId;
		this.subcenterId = subcenterId;
		this.fatherHusbandName = fatherHusbandName;
		this.email = email;
		this.mobileNo = mobileNo;
		this.economicStatus = economicStatus;
		this.category = category;
		this.beneficiaryAddress = beneficiaryAddress;
		this.uidNumber = uidNumber;
		this.pincode = pincode;
		this.lmpDate = lmpDate;
		this.eidNumber = eidNumber;
		this.anmId = anmId;
		this.ward = ward;
		this.town = town;
		this.mctsPregnantMotherServiceUpdates = mctsPregnantMotherServiceUpdates;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id", nullable = false)
	public MotherCase getMotherCase() {
		return this.motherCase;
	}

	public void setMotherCase(MotherCase motherCase) {
		this.motherCase = motherCase;
	}

	@Column(name = "mcts_id", length = 20)
	public String getMctsId() {
		return this.mctsId;
	}

	public void setMctsId(String mctsId) {
		this.mctsId = mctsId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", length = 13)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "village_id")
	public String getVillageId() {
		return this.villageId;
	}

	public void setVillageId(String villageId) {
		this.villageId = villageId;
	}

	@Column(name = "subcenter_id")
	public String getSubcenterId() {
		return this.subcenterId;
	}

	public void setSubcenterId(String subcenterId) {
		this.subcenterId = subcenterId;
	}

	@Column(name = "father_husband_name")
	public String getFatherHusbandName() {
		return this.fatherHusbandName;
	}

	public void setFatherHusbandName(String fatherHusbandName) {
		this.fatherHusbandName = fatherHusbandName;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile_no", length = 20)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "economic_status")
	public String getEconomicStatus() {
		return this.economicStatus;
	}

	public void setEconomicStatus(String economicStatus) {
		this.economicStatus = economicStatus;
	}

	@Column(name = "category")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "beneficiary_address")
	public String getBeneficiaryAddress() {
		return this.beneficiaryAddress;
	}

	public void setBeneficiaryAddress(String beneficiaryAddress) {
		this.beneficiaryAddress = beneficiaryAddress;
	}

	@Column(name = "uid_number")
	public String getUidNumber() {
		return this.uidNumber;
	}

	public void setUidNumber(String uidNumber) {
		this.uidNumber = uidNumber;
	}

	@Column(name = "pincode", length = 6)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "lmp_date", length = 13)
	public Date getLmpDate() {
		return this.lmpDate;
	}

	public void setLmpDate(Date lmpDate) {
		this.lmpDate = lmpDate;
	}

	@Column(name = "eid_number")
	public String getEidNumber() {
		return this.eidNumber;
	}

	public void setEidNumber(String eidNumber) {
		this.eidNumber = eidNumber;
	}

	@Column(name = "anm_id", length = 20)
	public String getAnmId() {
		return this.anmId;
	}

	public void setAnmId(String anmId) {
		this.anmId = anmId;
	}

	@Column(name = "ward")
	public String getWard() {
		return this.ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	@Column(name = "town")
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mctsPregnantMother")
	public Set<MctsPregnantMotherServiceUpdate> getMctsPregnantMotherServiceUpdates() {
		return this.mctsPregnantMotherServiceUpdates;
	}

	public void setMctsPregnantMotherServiceUpdates(
			Set<MctsPregnantMotherServiceUpdate> mctsPregnantMotherServiceUpdates) {
		this.mctsPregnantMotherServiceUpdates = mctsPregnantMotherServiceUpdates;
	}

}
