package org.motechproject.mcts.integration.hibernate.model;

// Generated May 26, 2014 2:25:24 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MctsPregnantMother generated by hbm2java
 */
@Entity
@Table(name = "mother_case_mcts_update", schema = "report")
public class MotherCaseMctsUpdate implements java.io.Serializable {

	/**
	 * case_id, , 2 columns full_mcts_id, mcts_id, authorized 
	 */
	private static final long serialVersionUID = -8318971109619756076L;
	private Integer id;
	private MotherCase motherCase;
	private String mctsId;
	private MotherCaseMctsAuthorizedStatusLookup motherCaseMctsAuthorizedStatus;	
	private String fullMctsId;

	
	@JoinColumn(name = "full_mcts_id")
	public String getFullMctsId() {
		return fullMctsId;
	}

	public void setFullMctsId(String fullMctsId) {
		this.fullMctsId = fullMctsId;
	}

	public MotherCaseMctsUpdate() {
	}

	public MotherCaseMctsUpdate(Integer id, MotherCase motherCase,
			 String mctsId, String fullMctsId,
			MotherCaseMctsAuthorizedStatusLookup motherCaseMctsAuthorizedStatus) {
		super();
		this.id = id;
		this.motherCase = motherCase;
		this.mctsId = mctsId;
		this.fullMctsId = fullMctsId;
		this.motherCaseMctsAuthorizedStatus = motherCaseMctsAuthorizedStatus;
	}



	@SequenceGenerator(name = "generator", sequenceName = "mcts_pregnant_mother_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_id")
	public MotherCase getMotherCase() {
		return this.motherCase;
	}

	public void setMotherCase(MotherCase motherCase) {
		this.motherCase = motherCase;
	}
	
	


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "case_authorized_status")
	public MotherCaseMctsAuthorizedStatusLookup getMotherCaseMctsAuthorizedStatus() {
		return this.motherCaseMctsAuthorizedStatus;
	}

	public void setMotherCaseMctsAuthorizedStatus(
			MotherCaseMctsAuthorizedStatusLookup motherCaseMctsAuthorizedStatus) {
		this.motherCaseMctsAuthorizedStatus = motherCaseMctsAuthorizedStatus;
	}

	@Column(name = "mcts_id")
	public String getMctsId() {
		return this.mctsId;
	}

	public void setMctsId(String mctsId) {
		this.mctsId = mctsId;
	}
}